version: '3.8'

services:
  product-service:
    build:
      context: ./product-service
    image: product-service:latest
    container_name: product-service
    ports:
      - "8080:8080"
    depends_on:
      - order-service
      - cache-service
    networks:
      - app-network

  order-service:
    build:
      context: ./order-service
    image: order-service:latest
    container_name: order-service
    ports:
      - "8081:8081"
    depends_on:
      - cache-service
    networks:
      - app-network

  cache-service:
    build:
      context: ./cache-service
    image: cache-service:latest
    container_name: cache-service
    ports:
      - "8084:8084"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

