version: '3.8'

services:
  product-service:
    build:
      context: ./product-service
    image: product-service:latest
    container_name: product-service
    ports:
      - "8080:8080"
    depends_on:
      - order-service
      - cache-service
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - app-network

  order-service:
    build:
      context: ./order-service
    image: order-service:latest
    container_name: order-service
    ports:
      - "8081:8081"
    depends_on:
      - cache-service
    networks:
      - app-network

  cache-service:
    build:
      context: ./cache-service
    image: cache-service:latest
    container_name: cache-service
    ports:
      - "8084:8084"
    networks:
      - app-network

  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - app-network

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: "redis-exporter"
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "9121:9121"
    depends_on:
      - redis
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: "prometheus"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - redis-exporter
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

