-- Create the category table
CREATE TABLE categories (
                            id BIGINT AUTO_INCREMENT PRIMARY KEY,
                            name VARCHAR(255) NOT NULL
);

-- Create the products table with a foreign key to the categories table
CREATE TABLE products (
                          id BIGINT AUTO_INCREMENT PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          description TEXT,
                          price DECIMAL(10, 2) NOT NULL,
                          category_id BIGINT,
                          FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- Insert sample categories
INSERT INTO categories (name) VALUES
                                  ('Electronics'),
                                  ('Computers'),
                                  ('Gaming'),
                                  ('Home Appliances'),
                                  ('Books');

-- Insert 500 sample data for products in the 'Electronics' category
INSERT INTO products (name, description, price, category_id)
VALUES
    ('Apple iPhone 15 Pro', 'The latest iPhone with A17 Bionic chip, titanium design, and advanced camera features.', 999.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Samsung Galaxy S23 Ultra', 'Flagship smartphone with Snapdragon 8 Gen 2 processor, 200MP camera, and S Pen.', 1199.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Sony WH-1000XM5 Headphones', 'Noise-canceling wireless headphones with superior sound quality and 30-hour battery life.', 399.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Bose QuietComfort 45', 'Noise-canceling over-ear headphones with 24-hour battery life and superior sound.', 329.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Sony PlayStation 5', 'Next-gen gaming console with lightning-fast load times and ray-tracing support.', 499.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('LG OLED65CXPUA Alexa Built-In CX 65" 4K Smart OLED TV', '65-inch OLED TV with perfect black and infinite contrast.', 1799.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Samsung Galaxy Watch 5', 'Smartwatch with heart rate tracking, GPS, and sleep monitoring.', 279.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Apple AirPods Pro', 'Wireless earbuds with Active Noise Cancellation and Adaptive Transparency.', 249.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('GoPro HERO10 Black', 'Action camera with 5.3K video resolution, HyperSmooth 4.0, and waterproof design.', 499.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Amazon Echo Show 8', 'Smart display with Alexa, perfect for video calls, smart home control, and entertainment.', 129.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Apple MacBook Air M1', 'Laptop with Apple M1 chip, Retina display, and up to 18 hours of battery life.', 999.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Apple iPad Pro 12.9" (5th Gen)', 'Tablet with M1 chip, Liquid Retina XDR display, and 5G support.', 1099.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Sony A7 III Mirrorless Camera', 'Full-frame mirrorless camera with 24.2MP sensor and 4K video recording.', 1999.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Fitbit Charge 5', 'Fitness tracker with heart rate monitoring, built-in GPS, and sleep tracking.', 149.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Logitech MX Master 3S', 'Ergonomic wireless mouse with ultra-fast scrolling and customizable buttons.', 99.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('HP Spectre x360 13', 'Convertible laptop with Intel Core i7, 16GB RAM, and 512GB SSD.', 1599.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Razer Blade 15 Advanced', 'Gaming laptop with Intel Core i7, RTX 3080, and 4K OLED touch display.', 2499.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Bose SoundLink Revolve+ II', 'Portable Bluetooth speaker with deep, immersive sound and up to 17 hours of battery life.', 329.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Google Pixel 6', 'Smartphone with Google Tensor chip, excellent camera capabilities, and 5G support.', 599.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Apple TV 4K', '4K HDR streaming device with Dolby Vision and Dolby Atmos support.', 179.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Sony Bravia XR A90J OLED TV', '65-inch OLED TV with Google TV, perfect black levels, and bright colors.', 2299.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('DJI Mavic Air 2', 'Drone with 4K camera, 48MP photos, and 34-minute flight time.', 799.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Samsung Galaxy Z Fold 4', 'Foldable smartphone with a 7.6-inch Dynamic AMOLED screen and 5G support.', 1799.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Microsoft Surface Pro 7', '2-in-1 laptop with Intel Core i5, 8GB RAM, and 128GB SSD.', 749.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Samsung 75-Inch QLED Smart TV', 'Smart TV with Quantum Dot technology, 4K resolution, and built-in Alexa.', 2299.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Nikon D850 DSLR Camera', 'Full-frame DSLR camera with 45.7MP sensor and 4K UHD video.', 2999.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Samsung Galaxy Tab S8 Ultra', '10.5-inch Android tablet with a stunning AMOLED display and S Pen support.', 999.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Epson EcoTank ET-4760', 'Wireless all-in-one printer with cartridge-free printing and low cost-per-page.', 499.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('JBL Charge 5', 'Waterproof Bluetooth speaker with JBL Bass Radiators and up to 20 hours of playtime.', 179.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Apple Watch Ultra', 'Durable smartwatch with titanium case, larger display, and advanced health tracking features.', 799.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Sony X900H 65-inch 4K UHD Smart TV', 'Smart TV with 4K HDR and Game Mode for seamless gaming experience.', 1099.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Sony A7R IV Mirrorless Camera', '45.7MP full-frame mirrorless camera with advanced autofocus and 4K video.', 3499.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Amazon Fire HD 10 Tablet', '10.1-inch tablet with Full HD display, 64GB storage, and Alexa built-in.', 149.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Bose Noise Cancelling Headphones 700', 'Wireless headphones with adjustable noise cancellation and 20-hour battery life.', 379.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Nintendo Switch OLED', 'Gaming console with a vibrant 7-inch OLED screen and enhanced audio for portable or docked play.', 349.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Apple iMac 24-inch M1', 'All-in-one desktop computer with Retina display and Apple M1 chip.', 1299.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Oculus Quest 2', 'Standalone VR headset with 64GB storage and immersive gameplay experiences.', 299.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Logitech C920S HD Pro Webcam', 'Full HD webcam with built-in privacy shutter and stereo audio.', 69.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Canon EOS R6 Mark II', 'Full-frame mirrorless camera with 24.2MP sensor and 4K video recording.', 2499.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Dell UltraSharp U2720Q 27-Inch 4K Monitor', 'High-end 27-inch monitor with 4K resolution and ultra-thin bezels.', 599.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Samsung 970 EVO Plus 1TB NVMe SSD', 'High-performance solid-state drive with read speeds up to 3500MB/s.', 129.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Apple Magic Keyboard for iPad Pro', 'Wireless keyboard with a trackpad, backlit keys, and USB-C port for charging.', 299.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Acer Predator Helios 300', 'High-performance gaming laptop with Intel Core i7 and NVIDIA GeForce RTX 3060.', 1499.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Samsung T7 Portable SSD 1TB', 'Portable solid-state drive with 1050MB/s read speed and shock resistance.', 109.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Canon EOS 90D DSLR Camera', 'DSLR camera with 32.5MP sensor and 4K video capabilities.', 1299.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Anker PowerCore 10000 PD Redux', 'Compact portable charger with USB-C and 10000mAh battery capacity.', 39.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('LG 34WN80C-B 34-Inch Curved UltraWide Monitor', '34-inch curved monitor with 1440p resolution and HDR10 support.', 349.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Vizio 65-Inch 4K UHD Smart TV', 'Smart TV with 4K resolution and built-in Alexa voice control.', 799.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Razer Kraken Ultimate RGB Headset', 'Gaming headset with THX Spatial Audio, noise-canceling mic, and customizable RGB lighting.', 129.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Corsair Vengeance LPX 16GB DDR4 RAM', '16GB high-performance memory for gaming and multitasking.', 69.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Philips Sonicare DiamondClean Smart Toothbrush', 'Electric toothbrush with smart sensors and multiple modes for enhanced oral care.', 229.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Sennheiser Momentum 3 Wireless', 'High-quality wireless headphones with noise cancellation and superior sound quality.', 399.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('TCL 6-Series 55-Inch QLED Smart TV', 'QLED TV with 4K resolution, Dolby Vision, and integrated Roku smart features.', 749.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Sony Xperia 1 III Smartphone', 'Flagship Android phone with 4K OLED display and professional-grade camera system.', 1299.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('MSI GE76 Raider Gaming Laptop', 'Gaming laptop with Intel Core i9 and NVIDIA RTX 3080 for exceptional performance.', 2299.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Bose 700 Series Soundbar', 'Soundbar with Alexa voice control, deep bass, and 4K pass-through HDMI.', 799.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Garmin Fenix 6 Pro Solar Smartwatch', 'Smartwatch with solar charging, GPS, and 14-day battery life.', 699.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Asus ROG Strix XG438Q 43-Inch Gaming Monitor', 'Ultra-wide gaming monitor with 4K resolution and 120Hz refresh rate.', 899.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Apple AirPods Max', 'Over-ear wireless headphones with Active Noise Cancellation and high-fidelity sound.', 549.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Bose Soundbar 500', 'Slim soundbar with Alexa built-in, ideal for small spaces with excellent sound quality.', 499.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Harman Kardon Onyx Studio 6', 'Portable Bluetooth speaker with iconic design, 8-hour playtime, and deep bass.', 349.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Acer Nitro 5 Gaming Laptop', 'Gaming laptop with Intel Core i5, 8GB RAM, and NVIDIA GeForce GTX 1650.', 799.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Samsung Galaxy A52 5G', 'Mid-range smartphone with 5G support, 120Hz Super AMOLED display, and quad-camera setup.', 399.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('LG 27GL83A-B 27-Inch Gaming Monitor', '27-inch monitor with 144Hz refresh rate and 1ms response time, perfect for gaming.', 379.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Anker Soundcore Liberty Air 2 Pro', 'True wireless earbuds with noise cancellation and 26-hour playtime.', 129.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Nvidia Shield TV Pro', '4K HDR streaming media player with Android TV, gaming, and voice search support.', 199.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Apple Magic Mouse 2', 'Wireless mouse with Bluetooth connectivity and multi-touch surface for intuitive control.', 79.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('BenQ ZOWIE XL2411P 24-Inch Gaming Monitor', '24-inch gaming monitor with 144Hz refresh rate and ultra-low latency.', 249.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Bose QuietComfort 35 II', 'Noise-canceling headphones with Alexa and Google Assistant integration.', 299.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Beats Fit Pro', 'True wireless earbuds with custom spatial audio and deep bass.', 199.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Turtle Beach Stealth 600 Gen 2', 'Wireless gaming headset with high-quality audio and lag-free wireless connection.', 99.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Jabra Elite 85t True Wireless Earbuds', 'Premium true wireless earbuds with hybrid active noise cancellation.', 229.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('iRobot Roomba i7+', 'Robot vacuum with smart mapping and self-emptying bin for hassle-free cleaning.', 799.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Ecovacs Deebot N8+', 'Smart robotic vacuum with laser navigation and mopping function for all-around cleaning.', 499.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Logitech G Pro X Gaming Headset', 'Pro-level gaming headset with Blue Voice microphone technology and 7.1 surround sound.', 129.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Garmin Forerunner 945', 'Advanced GPS smartwatch for athletes with heart rate monitoring and music storage.', 599.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Sony E 50mm F1.8 OSS Lens', 'Compact prime lens for Sony mirrorless cameras with optical steady shot.', 348.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Apple HomePod Mini', 'Compact smart speaker with premium sound quality and Siri integration.', 99.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Logitech G915 TKL Wireless Gaming Keyboard', 'Low-profile mechanical gaming keyboard with RGB lighting and advanced wireless connectivity.', 229.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Nikon D7500 DSLR Camera', 'DSLR camera with 20.9MP sensor, 4K UHD video, and 8fps continuous shooting.', 999.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Bose Portable Smart Speaker', 'Portable Bluetooth speaker with Alexa and Google Assistant support.', 349.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Nvidia GeForce RTX 3090', 'High-performance graphics card with 24GB of GDDR6X memory for ultra-high-definition gaming.', 1499.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Garmin Venu 2', 'Smartwatch with GPS, health monitoring, and up to 11-day battery life.', 399.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Microsoft Surface Laptop 4', 'Laptop with Intel Core i7, 16GB RAM, and 512GB SSD for productivity and entertainment.', 1599.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('GoPro HERO9 Black', 'Action camera with 5K video resolution and HyperSmooth 3.0 stabilization.', 399.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Philips Hue White and Color Ambiance Starter Kit', 'Smart lighting kit with 16 million colors and voice control integration.', 199.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Logitech G602 Wireless Gaming Mouse', 'Wireless gaming mouse with 11 programmable buttons and long battery life.', 79.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Fitbit Inspire 2', 'Fitness tracker with 24/7 heart rate tracking and 10-day battery life.', 89.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Seagate Backup Plus 2TB External Hard Drive', 'Portable external hard drive with fast transfer speeds and reliable backup features.', 69.99, (SELECT id FROM categories WHERE name = 'Electronics')),
    ('Asus ROG Strix GTX 1660 Ti', 'Graphics card with 6GB GDDR5 memory and DirectX 12 support for smooth gaming.', 249.99, (SELECT id FROM categories WHERE name = 'Electronics'));
